// Global
export const SET_REFERENCE_DATA = 'SET_REFERENCE_DATA'

// Measures
export const SET_MEASURES = 'SET_MEASURES'
export const SET_MEASURE_FETCH_ERROR = 'SET_MEASURE_FETCH_ERROR'
export const SET_MEASURE_CREATE_ERROR = 'SET_MEASURE_CREATE_ERROR'
export const SET_NEW_MEASURE = 'SET_NEW_MEASURE'
export const SET_NEW_MEASURE_ATTRIBUTE = 'SET_NEW_MEASURE_ATTRIBUTE'
export const CLEAR_NEW_MEASURE = 'CLEAR_NEW_MEASURE'
export const SET_NEW_MEASURE_CURRENT_TAB = 'SET_NEW_MEASURE_CURRENT_TAB'
