// Global
export const SET_REFERENCE_DATA = 'SET_REFERENCE_DATA'

// Measures
export const SET_MEASURES = 'SET_MEASURES'
export const SET_MEASURE_FETCH_ERROR = 'SET_MEASURE_FETCH_ERROR'
export const SET_MEASURE_CREATE_ERROR = 'SET_MEASURE_CREATE_ERROR'
export const SET_MEASURE_SAVE_ERROR = 'SET_MEASURE_SAVE_ERROR'
export const SET_MEASURE = 'SET_MEASURE'
export const SET_MEASURE_ATTRIBUTE = 'SET_MEASURE_ATTRIBUTE'
export const CLEAR_MEASURE = 'CLEAR_MEASURE'
export const SET_MEASURE_CURRENT_TAB = 'SET_MEASURE_CURRENT_TAB'
export const SAVE_MEASURE = 'SAVE_MEASURE'
