// Global
export const SET_REFERENCE_DATA = 'SET_REFERENCE_DATA'

// Measures
export const SET_MEASURES = 'SET_MEASURES'
export const SET_MEASURE_FETCH_ERROR = 'SET_MEASURE_FETCH_ERROR'
export const SET_MEASURE_CREATE_ERROR = 'SET_MEASURE_CREATE_ERROR'
export const SET_MEASURE_SAVE_ERROR = 'SET_MEASURE_SAVE_ERROR'
export const SET_MEASURE = 'SET_MEASURE'
export const SET_MEASURE_ATTRIBUTE = 'SET_MEASURE_ATTRIBUTE'
export const CLEAR_MEASURE = 'CLEAR_MEASURE'
export const SET_MEASURE_CURRENT_TAB = 'SET_MEASURE_CURRENT_TAB'
export const SAVE_MEASURE = 'SAVE_MEASURE'

// Students
export const SET_STUDENTS = 'SET_STUDENTS'
export const SET_STUDENT_FETCH_ERROR = 'SET_STUDENT_FETCH_ERROR'
export const SET_STUDENT_CREATE_ERROR = 'SET_STUDENT_CREATE_ERROR'
export const SET_STUDENT_SAVE_ERROR = 'SET_STUDENT_SAVE_ERROR'
export const SET_STUDENT = 'SET_STUDENT'
export const CLEAR_STUDENT = 'CLEAR_STUDENT'
export const SAVE_STUDENT = 'SAVE_STUDENT'
